---
name: Kubernetes
kramdown:
  auto_ids: true
  toc_levels: 1..6
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: '1'
  html_to_native: true
  syntax_highlighter: rouge
defaults:
- scope:
    path: ''
  values:
    version: v1.2
    githubbranch: release-1.2
    docsbranch: master
- scope:
    path: docs
  values:
    layout: docwithnav
    showedit: true
permalink: pretty
baseurl: "/"
port: 4000
collections:
  posts:
    output: true
    permalink: "/:categories/:year/:month/:day/:title/"
exclude:
- vendor
